# ===================================================================================
# ==         README: Progressive Promotion Pipeline (Definitive Version)         ==
# ===================================================================================
#
# This is the definitive pipeline for this application.
#
# CORRECTIONS (Final Architecture):
# 1.  **Correct Stage Separation:** The 'Build' and 'Deploy_Dev' stages are now
#     separate again. This is critical to ensure that Pull Requests to 'dev' and
#     'release/*' branches correctly trigger ONLY the build/validation stage, without
#     attempting any deployments.
# 2.  **Automatic Project Name:** The hardcoded 'microserviceProjectName' variable
#     has been removed. The promotion templates now use the built-in '$(System.TeamProject)'
#     variable, making this pipeline cleaner and more portable.
#
# ===================================================================================

trigger:
  branches:
    include:
      - dev
      - release/*
  tags:
    include:
      - v*.*.*
pr:
  branches:
    include:
      - dev
      - release/*

resources:
  repositories:
    - repository: templates
      type: git
      name: YourPlatformProject/cicd-platform
      ref: main

variables:
  # The 'microserviceProjectName' variable is no longer needed.
  - name: serviceName
    value: 'manubank-transactions-microservice'
  - name: acrName
    value: 'acrmanubankdev'
  - name: chartPath
    value: 'charts/common-app'
  # ... etc.

stages:
# STAGE 1: Build the artifact. This runs for PRs, dev, and release builds.
- stage: Build_Artifact
  displayName: 'Build and Validate Artifact'
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
  jobs:
  - template: pipelines/build/kotlin-docker-build.yml@templates
    parameters:
      # ... snyk and other build parameters

# STAGE 2: Deploy to the Dev environment.
- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Build_Artifact
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - deployment: DeployToDevAKS
    # ... (standard dev deployment job)

# STAGE 3: MANUAL GATE to promote the 'dev' build to a 'release'
- stage: Promote_To_QA
  displayName: 'Promote to QA'
  dependsOn: Deploy_Dev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - deployment: Approval_and_Create_Release
    environment: 'Promote to QA Gate - $(serviceName)'
    pool: { name: 'MB_DevOps' }
    strategy:
      runOnce:
        deploy:
          steps:
          # Call the step template without the project name parameter.
          - template: pipelines/management/create-release-steps.yml@templates
            parameters:
              repositoryName: $(serviceName)

# STAGE 4: Deploy the Release Candidate to QA.
- stage: Deploy_QA
  displayName: 'Deploy Release Candidate to QA'
  dependsOn: Build_Artifact
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  jobs:
  - deployment: Deploy_QA_East
    # ... (standard QA deployment job)

# STAGE 5: MANUAL GATE to promote the 'release' build to 'main'
- stage: Promote_To_Prod
  displayName: 'Promote to Prod'
  dependsOn: Deploy_QA
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
  jobs:
  - deployment: Approval_and_Finalize_Release
    environment: 'Promote to Prod Gate - $(serviceName)'
    pool: { name: 'MB_DevOps' }
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/management/finalize-release-steps.yml@templates
            parameters:
              repositoryName: $(serviceName)
              releaseBranchName: $(Build.SourceBranchName)

# STAGE 6: Promote the artifact and Deploy to Production.
- stage: Deploy_Prod
  displayName: 'Promote and Deploy to Production'
  dependsOn: []
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  jobs:
  - job: Promote_Image
    # ... (promotion job)
  - deployment: Deploy_Prod_East
    # ... (production deployment job)