# ===================================================================================
# ==         README: Create Release Pipeline (Final, Corrected Syntax)           ==
# ===================================================================================
#
# PURPOSE:
# This is the definitive pipeline for starting a new release for a single microservice.
#
# CORRECTION (Definitive YAML Syntax Fix):
# This version corrects the YAML structure for all 'Bash@3' tasks. The 'env' block
# has been moved to its correct position as a direct child of the task, at the same
# level as 'inputs' and 'displayName'. This resolves all previous YAML parsing and
# "command not found" errors related to environment variables.
#
# ===================================================================================

trigger: none
pr: none

parameters:
- name: microserviceProjectName
  displayName: 'Microservice Project Name'
  type: string
  default: 'API Engineering'
- name: repositoryName
  displayName: 'Microservice to Release'
  type: string
  default: 'manubank-transactions-microservice'
  values:
    - order-service
    - payment-service
    - manubank-transactions-microservice

pool:
  name: 'MB_DevOps'

jobs:
- job: CreateReleaseForSingleService
  displayName: 'Create Release for ${{ parameters.repositoryName }}'
  workspace:
    clean: all
  
  steps:
  # Step 1: Check out the platform repo first.
  - checkout: self
    path: 'platform'

  # Step 2: Install tools.
  - task: Bash@3
    displayName: 'Install Tools'
    inputs:
      targetType: 'inline'
      script: |
        echo '{ "name": "create-release-tools", "version": "1.0.0" }' > package.json
        npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec

  # ============================ THE FIX IS HERE ============================
  # Step 3: Manually clone the target microservice repo.
  - task: Bash@3
    displayName: 'Clone & Checkout Microservice Repo'
    # 'env' is at the same level as 'inputs'.
    env:
      GIT_TOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        set -e
        # IMPORTANT: Replace 'YourOrgName' with your actual organization name.
        PROJECT_NAME_ENCODED=$(echo "${{ parameters.microserviceProjectName }}" | sed 's/ /%20/g')
        REPO_URL="https://x-token-auth:$(GIT_TOKEN)@dev.azure.com/YourOrgName/${PROJECT_NAME_ENCODED}/_git/${{ parameters.repositoryName }}"
        
        git clone "$REPO_URL" service-repo
        
        cd service-repo
        git checkout develop
  # =======================================================================

  # Step 4: Copy the central config file.
  - task: CopyFiles@2
    displayName: 'Copy Central .releaserc.json'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/platform/config'
      Contents: 'common.releaserc.json'
      TargetFolder: '$(System.DefaultWorkingDirectory)/service-repo'
      OverWrite: true
  - task: PowerShell@2
    displayName: 'Rename config file'
    inputs:
      targetType: 'inline'
      script: 'Rename-Item -Path "$(System.DefaultWorkingDirectory)/service-repo/common.releaserc.json" -NewName ".releaserc.json"'

  # Step 5: Run semantic-release.
  - task: Bash@3
    displayName: 'Calculate Next Version'
    # 'env' is at the same level as 'inputs'.
    env:
      GIT_TOKEN: $(System.AccessToken)
      GH_TOKEN: $(System.AccessToken)
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/service-repo'
      targetType: 'inline'
      script: 'npx semantic-release || true'
  
  # Step 6: Read the version and create the release branch.
  - task: Bash@3
    displayName: 'Create and Push Release Branch'
    # 'env' is at the same level as 'inputs'.
    env:
      GIT_TOKEN: $(System.AccessToken)
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/service-repo'
      targetType: 'inline'
      script: |
        set -e
        if [ -f "next-version.txt" ]; then
          NEXT_VERSION=$(cat next-version.txt)
          echo "Found new version: $NEXT_VERSION. Creating release branch."

          git config --global user.email "pipeline@azuredevops.com"
          git config --global user.name "Azure DevOps Pipeline"
          
          RELEASE_BRANCH="release/$NEXT_VERSION"
          git checkout -b $RELEASE_BRANCH

          REPO_URL=$(git config --get remote.origin.url)
          AUTH_REPO_URL="https://x-token-auth:$(GIT_TOKEN)@${REPO_URL#https://}"
          git push $AUTH_REPO_URL $RELEASE_BRANCH
        else
          echo "No new changes to release."
        fi
